Sense Enterprise April 2018 updates
qlik-oss/server-side-extension pull request #31
Opened 2018-03-12 13:01 UTC by josefinestalqlik

In the Sense Enterprise April 2018 release, it's no longer needed to restart Qlik engine service when capabilities of a plugin are changed/added/deleted. This PR includes necessary updates in the documentation.

**OBS! Wait with merging this PR!**

### Status
```
[ ] Under development
[x] Waiting for code review
[x] Waiting for merge
```
### Information
```
[ ] Contains breaking changes
[ ] Contains new API(s)
[x] Contains documentation
[ ] Contains test
[ ] Contains examples
```

2018-03-12 13:17 UTC, qlik-aoh requested changes

2018-03-12 13:17 UTC, qlik-aoh commented on docs/communication_flow.md
> +    * Configuration using Settings.ini or QMC and earlier releases: The SSE plugin must be running before the Qlik Engine service is started. Any changes in the configuration requires a restart of th
From April 2018 we will retry connections to all plugins, both from QRS or settings.ini, so the plugin is not required to run before starting engine.

2018-03-12 13:17 UTC, qlik-aoh commented on docs/README.md
> -This means that the server (that is, the plugin) must be started and running before the Qlik engine is started.
Perhaps a "Before April 2018"-conditional instead of removing totally?

2018-03-12 13:40 UTC, LinneaStovring-Nielsen commented on docs/configuration.md
> +You must configure SSE plugins, referred to by Qlik as analytic connections, in the Qlik Management Console (QMC) or using the Qlik Repository Service API.
Or in the settings.ini file. And in desktop you still need to restart.

2018-03-14 11:35 UTC, LinneaStovring-Nielsen approved these changes

2018-04-20 08:55 UTC, qlik-aoh approved these changes

2018-04-23 08:52 UTC, merged